[package]
name = "game_engine_glium"
version = "0.1.0"
authors = ["Vladislav Gladkiy <kbga5lh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.26.0"
wavefront_obj = "7.0.0"